security:

    encoders:
        AppBundle\Entity\User: bcrypt


    providers:

        users:
            entity: { class: AppBundle\Entity\User, property: email }


    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: user_login
                check_path: user_login

            guard:
                authenticators:
                    - 'facebook_authenticator'

            logout:
                path: /logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/order, roles: ROLE_USER }
        - { path: ^/user/orders, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
