# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    facebook_authenticator:
        class: AppBundle\Service\FacebookAuthenticator
        autowire: true

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Controller,Entity,Repository,Tests}'

    AppBundle\EventListener\FacebookPictureUpdateListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLoginSuccess }